### ISSUE TITLE
Artifact in eagle image

### ISSUE THREAD

**Issue by abevoelker** [goshacmd/nsa_panel#1]
There is a version without an artifact on the EFF's Flickr page: https://secure.flickr.com/photos/hughelectronic/3532485014/in/set-72157603862200764

**Comment by goshacmd** [comment]
Thank you. :smile:

**Comment by abevoelker** [comment]
No problem, I was actually just making a t-shirt on Zazzle with the same logo so I was aware of the problem :smile:
