### ISSUE TITLE
"Full Accordance with the Law" compliance check

### ISSUE THREAD

**Issue by colemickens** [goshacmd/nsa_panel#4]
I'm sorry, as a site operator, I want to make sure the government does not have "direct access" to my servers. I will only allow access "in accordance with law".

Thus, this project needs a page before the NSA may the output that allows them to confirm they've received a FISA warrant.

I wouldn't bother with the whole "accountability" aspect of that feature; and I wouldn't prioritize ~~easy~~ reporting on the use of it either. Actually, a big HTML5 rubber stamp stamping down on something would be kinda cool, as the page submits.

**Comment by goshacmd** [comment]
Thanks for the idea! :+1:
