### ISSUE TITLE
Different roles for users

### ISSUE THREAD

**Issue by residuum** [goshacmd/nsa_panel#5]
If a user is high-ranking enough, she may be able to order a drone strike on a user, if content is suspicious enough.

**Comment by goshacmd** [comment]
Introducing proper ACL would probably involve implementing a db-backed authentication, which would be overload for the purpose of this simple project.

However, the ability to order drone strikes is really a good sounding feature and might find a lot of use. Maybe everyone who accesses /nsa_panel should be able to use it?

**Comment by sysr-q** [comment]
There's a whole plethora of unexplored features here that are really just the tip of the iceberg.
Drone strikes, SWAT teams; you name it!

**Comment by goshacmd** [comment]
I just added it so that any NSA agent can order drone strikes on suspicious persons. Yay rule of law and war on terrorism.
