### ISSUE TITLE
Feature Request: IRS Audit Trigger

### ISSUE THREAD

**Issue by dolan** [goshacmd/nsa_panel#8]
I would like to be able to alert the IRS with a single click that this organization may be conservative, and/or terrorist. (Really that's the same thing)

Possible enhancement to this: key words in user names or data entered that automatically trigger IRS audit alerts.

**Comment by goshacmd** [comment]
Sounds like a good idea.

However, National Security Agency is meant to spy on **foreigners**. **Internal** Revenue Service, however, is about thieving **American's** money. Right?

So I don't quite think it makes a lot of sense for NSA to alert IRS about people who are not subject to IRS audits.

**Comment by Bramanga** [comment]
@dolan you might want to fork this as a separate gem, maybe irs_panel? 

Perhaps we should add some PRISM features as well. I personally find it more difficult to accuse somebody of being a terrorist based on their phone records. Email records are much easier to fabricate, so I think both the FBI and DHS might find PRISM features more useful. Could you add a 'Falsify Email Records' feature?

**Comment by goshacmd** [comment]
> @dolan you might want to fork this as a separate gem, maybe irs_panel?

It might be a good idea to create a whole suite of gems for gov't agency surveillance. NSA, DHS, FBI, IRS, DOJ, DOD, DOS, TSA, WH, etc.

Speaking of fabrication, it's not the thing the government would do. Damn no. More proper feature might be the one to **correct** all sorts of records (governments know better than you what you intended to say in that message you sent to your friend, after all!).

Though governments barely would need this. 

1) They don't really need to prove anything. They can just send the drone and say they _thought_ you were a terrorist. nsa_panel provides this lovely feature.

2) It's just easier to use terrorism as an excuse to make an Orwellian world, it's not necessary to accuse someone of something.

**Comment by hayesr** [comment]
All of these gems should depend on another to search for keywords. Perhaps it could lean on the Text gem to find occurrences of troubling words and phrases like _freedom_, _liberty_, _constitution_, _limited government_, _due process_, etc.

This would make it easier for our overlords to find what they are looking for (you know, eventually when they get around to looking through the data). Anytime we can help government be "more efficient" is a good thing!

Possible names for this gem: _freedom_search_, _patriot_act_

**Comment by goshacmd** [comment]
It would be out of scope of this simple project to add ability to search the entire DB for these words, I guess.
