### ISSUE TITLE
No Warrant button too restrictive

### ISSUE THREAD

**Issue by m1foley** [goshacmd/nsa_panel#9]
There are at least 2 situations where the No Warrant button is too restrictive:
1. Your department has a ["program warrant"](http://www.guardian.co.uk/commentisfree/2013/may/03/fisa-court-rubber-stamp-drones), which allows warrantless wiretapping on citizens (Note: this is the typical "happy path" use case).
2. At least one of the people in the discussion is believed (with 51% certainty) to be [currently outside the U.S.](http://www.theatlanticwire.com/technology/2013/06/nsa-prism-program/65994/), or has ever had correspondence with such a person.

**Comment by nwwatson** [comment]
I believe your enhancement request is still too restrictive. It might be more useful to make the 'I have not received a FISA warrant' path point to dashboard_proceed_path. Having the button allows the government to say "Hey, we have a check in place" while still getting the data they need to eavesdrop on citizens.

**Comment by goshacmd** [comment]
I agree. Maybe the button should say "I don't need a FISA warrant" instead of "I have not received a FISA warrant"?

**Comment by goshacmd** [comment]
I feel we don't need this law accordance check anymore.

> If the NSA wants "to listen to the phone," an analyst's decision is sufficient, without any other legal authorization required, Nadler said he learned.

http://news.cnet.com/8301-13578_3-57589495-38/nsa-admits-listening-to-u.s-phone-calls-without-warrants/

**Comment by goshacmd** [comment]
I think if the desire to wiretap Americans' phones is enough, it'd be surely enough to monitor foreigners' online data. Who needs these warrants, authorizations, and stuff.
